// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdizvumynqfacnhnootz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkaXp2dW15bnFmYWNuaG5vb3R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMTM4NTgsImV4cCI6MjA3NDg4OTg1OH0.LzF1gRGZZnZDp4rqtCdoXeEn34ZXseCoCmqYRj9jvhk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});